---
title: "R Notebook"
output: html_notebook
---

On essaie de comprendre avec leur example 
```{r}
links <- read.csv("Dataset1-Media-Example-EDGES.csv", header=T, as.is=T)
nodes <- read_csv("Dataset1-Media-Example-NODES.csv")

```


```{r}

View(links)
View(nodes)
View(base_trajet_1)
```
On va donc créer une base de donnée similaire à nodes 
```{r}

nodes_trajet <- base_trajet_total[, 1:2]
nodes_trajet <- unique(nodes_trajet)
View(nodes_trajet)

```

```{r}

head(nodes)
head(links)
nrow(nodes); length(unique(nodes$id))
nrow(links); nrow(unique(links[,c("from", "to")]))

links <- aggregate(links[,3], links[,-3], sum) 
links <- links[order(links$from, links$to),] 
colnames(links)[4] <- "weight"
rownames(links) <- NULL


```

```{r}

stop_id_metro_1  <- base_trajet_1$stop_id
temps_trajet_1 <- temps_trajet[temps_trajet$from_stop_id %in% stop_id_metro_1 & temps_trajet$to_stop_id %in% stop_id_metro_1 , ]

nodes_trajet_1 <- nodes_trajet[nodes_trajet$stop_id %in% stop_id_metro_1 & nodes_trajet$stop_id %in% stop_id_metro_1 , ]

```

```{r}
temps_trajet_1_igraph <- graph_from_data_frame(d=temps_trajet_1, vertices = nodes_trajet_1, directed = F)
```

```{r}
temps_trajet_1_igraph

vertex_1 <- V(temps_trajet_1_igraph)
```
```{r}
vertex_1
```


```{r}
temps_trajet_1_igraph
```

```{r}
plot(temps_trajet_1_igraph, edge.arrow.size=.4,vertex.label=NA)
```

```{r}
trajet_igraph <- graph_from_data_frame(d=temps_trajet, directed = F)
```

```{r}
class(trajet_igraph)
```

```{r}
trajet_igraph
```

```{r}
plot(trajet_igraph, edge.arrow.size=.4,vertex.label=NA)
```
