---
title: "Projet RATP"
output: html_notebook
---

Ajout des librairies 
```{r}

library("dplyr")
library("readr")
library("ggplot2")

```

Où sommes nous ? 

```{r}
getwd()
```



```{r}

routes <- read_csv("RATP_GTFS_FULL/routes.txt", col_names = TRUE)

```
```{r}
View(routes)
```

```{r}

stops <- read_csv("RATP_GTFS_FULL/stops.txt", col_names = TRUE)

```

```{r}
View(stops)
```

```{r}
transfers <- read_csv("RATP_GTFS_FULL/transfers.txt", col_names = TRUE)


```

```{r}
View(transfers)
```


```{r}
trips <- read_csv("RATP_GTFS_FULL/trips.txt", col_names = TRUE)
```
```{r}
View(trips)
```


```{r}

```

```{r}
library("ggplot2")
library("ggthemes")

```


Test de carte 
```{r}
test_carte <- ggplot(data = stops) +
  geom_path(aes(stop_lon, stop_lat),
            size = 0.5, alpha = .1) +
  coord_equal() +
  theme_map()

```

```{r}
test_carte
```
```{r}
test_carte2 <- ggplot(data = stops) +
  geom_point(aes(stop_lon, stop_lat, group = stop_id),
            size = 0.5, alpha = .1) +
  coord_equal() +
  theme_map()
```

```{r}
test_carte2
```


```{r}
devtools::install_github('ropensci/gtfsr')
```

```{r}
stop_times <- read_csv("RATP_GTFS_FULL/stop_times.txt", col_names = TRUE)
```

```{r}
library("leaflet")

```

```{r}
map <- leaflet() %>%
  # Add CartoDB background map
  addProviderTiles("CartoDB.DarkMatter") %>%  
  # Add a marker for each stop
  addCircleMarkers(lng= ~ stop_lon, lat= ~stop_lat, data = stops,
                   stroke = FALSE, fillOpacity = 0.5, radius =5 ) 
map  # Show the map
```

```{r}

## Problème pour déterminer quel type d'arret : métro ou bus 
stops_metro <- stops %>%
  filter(!grepl("\\d", stop_id))

routes_metro <- routes %>%
  filter(grepl("^L\\d", route_id))

shapes_metro <- shapes %>%
  filter(shape_id %in% trips$shape_id[trips$route_id %in% routes_metro$route_id]) %>%
  arrange(shape_id, shape_pt_sequence)
```


```{r}

View(stop_times)
```
```{r}
rm(full_base_bas)
```

Premier joint 
```{r}

full_base_bas <- stops %>%
  full_join(stop_times, by= "stop_id") %>%
  full_join(trips, by = "trip_id")

```

```{r}

full_base <- stops %>%
  full_join(stop_times, by= "stop_id") %>%
  full_join(trips, by = "trip_id")%>%
  full_join(routes, by = "route_id")


```

```{r}

full_base_metro <- full_base %>%
  filter (route_type == 1 | route_type== 2 )

```

```{r}
View(full_base_metro)
```

```{r}
full_base_metro$stop_code <- NULL

```

```{r}
full_base_metro$location_type <- NULL
full_base_metro$parent_station <- NULL 
full_base_metro$ shape_dist_traveled <- NULL 
full_base_metro$stop_headsign <- NULL 
```

```{r}
full_base_metro$ shape_id <- NULL 
full_base_metro$agency_id <- NULL 
full_base_metro$route_desc <- NULL 
full_base_metro$route_url<-NULL
full_base_metro$route_color<-NULL 
full_base_metro$route_text_color <-NULL 
```

```{r}
base_metro <- full_base_metro
```

```{r}
View(base_metro)
library(magrittr) 
library(dplyr)
```

```{r}
base_metro_map <- base_metro %>%
  distinct(stop_name, route_short_name, .keep_all = TRUE)
```

```{r}
View(base_metro_map)
```


```{r}
map_metro <- leaflet() %>%
  # Add CartoDB background map
  addProviderTiles("CartoDB.DarkMatter") %>%  
  # Add a marker for each stop
  addCircleMarkers(lng= ~ stop_lon, lat= ~stop_lat, data = base_metro_map,
                   stroke = FALSE, fillOpacity = 0.5, radius =5 ) 
map_metro  # Show the map
```


```{r}
base_metro_map$route_short_name = factor(base_metro_map$route_short_name)
library(forcats)
base_metro_map$route_short_name
```

```{r}
fct_relevel(base_metro_map$route_short_name, c(1, 2, 3, "3B", 4, 5, 6, 7, "7B", 8, 9, 10, 11, 12, 13, 14, "A", "B"))
```

```{r}
factpal=colorFactor(palette = c("#FFCD00", "#003CA6", "#837902", "#00AE41", "#CF009E", "#FF7E2E", "#6ECA97", "#FA9ABA", "#6ECA97", "#E19BDF", "#B6BD00", "#C9910D", "#704B1C", "#007852", "#6EC4E8", "#62259D", "#E2231A", "#7BA3DC"), 
            domain = base_metro_map$route_short_name, levels = levels(base_metro_map$route_short_name), ordered = TRUE, na.color = "#808080", alpha = FALSE)
```

```{r}
map_metro_color = leaflet() %>%
  # Add CartoDB background map
  addProviderTiles("CartoDB.DarkMatter") %>%  
  # Add a marker for each stop
  addCircleMarkers(lng= ~ stop_lon, lat= ~stop_lat, data = base_metro_map, stroke = FALSE, 
                   fillOpacity = 0.5, radius =3, color = ~ factpal(route_short_name)) %>% 
  addLegend(colors =c("#FFCD00", "#003CA6", "#837902", "#00AE41", "#CF009E", "#FF7E2E", "#6ECA97", "#FA9ABA", "#6ECA97", "#E19BDF", "#B6BD00", "#C9910D", "#704B1C", "#007852", "#6EC4E8", "#62259D", "#E2231A", "#7BA3DC"),
            labels = levels(base_metro_map$route_short_name),title = "Metro line Paris")
map_metro_color  # Show the map
```

